### ISSUE TITLE
Companion type insertAll: prototype => codegen

### ISSUE THREAD

**Issue by marcioendo** [objectos/orm#29]
## Tasks

- [x] OrmPojoInfo.of() returns Optional
- [x] CompanionType: className + insertable
- [x] generate class only, no methods
- [x] add the field/constructor
- [x] add static factory method
- [x] IsOrmInsertable: tableClassName, pojoClassName, superClassName
- [x] insertAll
